backend/makale/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
]

backend/otomasyon/urls.py
from django.contrib import admin
from django.urls import path ,include
from home.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/",include("user_op.urls")),
    path("",home,name="index"),
    path("ogrenci/",home,name="ogrenci"),
    path("akademisyen/",home,name="akademisyen"),
    path('articles/',include("makale.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

backend/user_op/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user_op"

urlpatterns = [
    path('register/',views.kayit,name = "register"),
    path('login/',views.giris,name = "login"),
    path('logout/',views.cikis,name = "logout"),
    #path('reset/<int:idim>/<int:kod>',views.parola_sifirlama,name = "reset"),
    #path('passrest/',views.pass_reset,name="passreset"),
    #path('kod/',views.email_gonder,name = "email_gonder"),
]

backend/user_op/forms.py
from django import forms
from django.forms import widgets

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı" , widget=forms.TextInput(attrs={'placeholder': 'Kullanıcı Adı', 'class': 'form-control'}))
    password = forms.CharField(label = "Parola",widget = forms.PasswordInput(attrs={'placeholder': 'Parola', 'class': 'form-control'}))


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Kullanıcı Adı")
    email = forms.EmailField(max_length=100,label = "Email")
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput)
    
    def clean(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm :
            raise forms.ValidationError("Parolalar Eşleşmiyor")

        values = {
            "username" : username,
            "password" : password,
            "email"  : email
        }
        return values

backend/user_op/views.py
from django.shortcuts import render
from django.shortcuts import render,HttpResponse,redirect
from django.utils.datastructures import MultiValueDictKeyError
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from all_users.models import *
# Create your views here.
def giris(request):
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username = username,password = password)
        if user is None:
            return render(request, "login.html",context)
        login(request,user)
        user_status_ = users_status.objects.filter(user= request.user)
        for i in user_status_:
            if i.status:
                return redirect("ogrenci")
            else:
                return redirect("akademisyen")
    return render(request, "login.html",context)

def kayit(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        newUser = User(username =username,email=email)
        newUser.set_password(password)
        newUser.save()
        login(request,newUser)
        return redirect("index")
    context = {
            "form" : form
        }
    return # render(request,"user_temp/register.html",context)

def cikis(request):
    logout(request)
    return redirect("index")

backend/user_op/templates/include/footer.html
    <footer class="footer">
        <div class="container">
            <div class="row">

                <div class="col-12 text-center">
                    <p>Yazarlar : Habip Eliş & Ahmet Enis Yeğin</p>
                    <p><a href="mailto:habipelis65@gmil.com">habipelis65@gmil.com</a></p>
                    <p><a href="mailto:habipelis65@gmil.com">habipelis65@gmil.com</a></p>
                </div>
            </div>
        </div>
    </footer>

backend/user_op/templates/include/header.html
{% load static %}
  <nav class="navbar navbar-expand-sm bg-light login-nav">
    <div class="container-fluid">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><img width="100px" src="{% static 'asset/img/logo.png' %}" alt="Fırat Ü. Logo"></a>

      </div>
      <div class="container">
        <ul class="navbar-nav">
          
          {% if request.user.is_authenticated %}
          <li class="nav-item ">
            <a class="nav-link" href="#">Profil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Kontrol Paneli</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Derslerim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/articles/">Bloglar Ve Makaleler</a>
          </li>
          <li class="nav-item">
             <a class="nav-link" href="{% url 'user_op:logout' %}">Çıkış</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_op:login' %}">Giriş</a>
          </li>
          {% endif %}
          
        </ul>
      </div>
  </nav>