backend/makale/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addarticle/',views.addArticle,name = "addarticle"),
    path('article/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateArticle,name = "update"),
    path('delete/<int:id>',views.deleteArticle,name = "delete"),
    path('',views.articles,name = "articles"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
]

backend/otomasyon/urls.py
from django.contrib import admin
from django.urls import path ,include
from home.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/",include("user_op.urls")),
    path("",home,name="index"),
    path("ogrenci/",home,name="ogrenci"),
    path("akademisyen/",home,name="akademisyen"),
    path('articles/',include("makale.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

backend/user_op/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user_op"

urlpatterns = [
    path('register/',views.kayit,name = "register"),
    path('login/',views.giris,name = "login"),
    path('logout/',views.cikis,name = "logout"),
    #path('reset/<int:idim>/<int:kod>',views.parola_sifirlama,name = "reset"),
    #path('passrest/',views.pass_reset,name="passreset"),
    #path('kod/',views.email_gonder,name = "email_gonder"),
]

backend/user_op/forms.py
from django import forms
from django.forms import widgets

class LoginForm(forms.Form):
    username = forms.CharField(label = "Kullanıcı Adı" , widget=forms.TextInput(attrs={'placeholder': 'Kullanıcı Adı', 'class': 'form-control'}))
    password = forms.CharField(label = "Parola",widget = forms.PasswordInput(attrs={'placeholder': 'Parola', 'class': 'form-control'}))


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Kullanıcı Adı")
    email = forms.EmailField(max_length=100,label = "Email")
    password = forms.CharField(max_length=20,label = "Parola",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="Parolayı Doğrula",widget = forms.PasswordInput)
    
    def clean(self):
        username = self.cleaned_data.get("username")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm :
            raise forms.ValidationError("Parolalar Eşleşmiyor")

        values = {
            "username" : username,
            "password" : password,
            "email"  : email
        }
        return values

backend/user_op/views.py
from django.shortcuts import render
from django.shortcuts import render,HttpResponse,redirect
from django.utils.datastructures import MultiValueDictKeyError
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from all_users.models import *
# Create your views here.
def giris(request):
    form = LoginForm(request.POST or None)
    context = {
        "form":form
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username = username,password = password)
        if user is None:
            return render(request, "login.html",context)
        login(request,user)
        user_status_ = users_status.objects.filter(user= request.user)
        for i in user_status_:
            if i.status:
                return redirect("ogrenci")
            else:
                return redirect("akademisyen")
    return render(request, "login.html",context)

def kayit(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        email = form.cleaned_data.get("email")
        newUser = User(username =username,email=email)
        newUser.set_password(password)
        newUser.save()
        login(request,newUser)
        return redirect("index")
    context = {
            "form" : form
        }
    return # render(request,"user_temp/register.html",context)

def cikis(request):
    logout(request)
    return redirect("index")

backend/user_op/templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Makale Ekle</button>
        </form>
    </div>
  </div>


{% endblock body %}

backend/user_op/templates/articles.html
{% extends "layout.html" %}

{% block body %}

<div class ="row">
    
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <h3>Makaleler</h3>
                <hr>
                </div>
        </div>
</div>
<div class ="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <form>
                 {% csrf_token %} 
                <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
              <button type="submit" class="btn btn-danger">Ara</button>
            </form>
      </div>
    </div>

</div>


{% if articles %}

{% for article in articles %}
<div class="row">
    <div class="col-md-10 offset-md-3">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a> 
        
      <!-- Author -->
      <p class="lead">
        
        {{article.author.username}} tarafından yayınlandı
      </p>

      <hr>

      <!-- Date/Time -->
      <p>{{article.created_date}}</p>
      <hr>
      <!-- Preview Image -->
      {% if article.article_image %}
      <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
      {% endif %}
     

      <hr>

      <!-- Post Content -->
      <p class="lead">
          {{article.content|safe|truncatewords:50}}
      </p>

      <a style ="float : right;" href="{% url 'article:detail' article.id %}" class ="btn btn-danger">Devamını Oku</a>
      <hr>
         
        </div>
      </div>
      </div>

{% endfor %}


{% else %}
<div class ="row">
    
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
<div class = "alert alert-danger">
   Makale Bulunamadı
</div>
</div>
</div>
</div>
{% endif %}

{% endblock body %}

backend/user_op/templates/dashboard.html
{% extends "layout.html" %}

{% block body %}
<h3>Kontrol Paneli</h3>
<hr>
<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>
</p>
<hr>
<a class = "btn btn-danger" href = "{% url 'article:addarticle' %}">Makale Ekle </a>
<hr>
{% if articles %}
<table class="table">
        <thead>
          <tr>
            <th scope="col">id</th>
            <th scope="col">Başlık</th>
            <th scope="col">Yazar</th>
            <th scope="col">Tarih</th>
            <th scope="col">Güncelle</th>
            <th scope="col">Sil</th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class = "btn btn-danger">Güncelle</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class = "btn btn-danger">Sil</a> </td>
              
          </tr>
          {% endfor %}
          
        </tbody>
      </table>
{% else %}

<div class = "alert alert-danger">
    Henüz bir makaleniz bulunmuyor...

</div>
{% endif %}



{% endblock body %}

backend/user_op/templates/homebase.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UE Otomasyon</title>
      <title>UE Anasayfa</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'asset/css/style.css' %}">
    <script src="{% static 'asset/js/make.js' %}"></script>
    {% block head %}
    
    {% endblock head %}
</head>
<body>
    {% block header %}
    {% include "include/header.html" %}
    {% endblock header %}
    {% block slider %}
    
    {% endblock slider %}
    {% block content %}
    
    {% endblock content %}
    {% block footer %}
    {% include "include/footer.html" %}
    {% endblock footer %}
</body>
</html>

backend/user_op/templates/index.html
{% extends "homebase.html" %}
{% block slider %}
{% load static %}
<div>
<img width="100%" src="{% static 'asset/img/firatuni.jpg' %}" alt="firatüniveristesi">
</div>
{% endblock slider %}

backend/user_op/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>UE BLOG-Makaleler</title>
</head>
<body>  
        {% include "includes/navbar.html" %}

        

        <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">
                
            {% if messages %}
                
                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}
                
                {% endif %}
            {% block body %}
            
            {% endblock body %}

        </div>
    

      <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="{% static 'js/bootstrap.min.js'%}"></script>
      <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
  
    </body>
</html>

backend/user_op/templates/login.html
{% extends "homebase.html" %}
{% block slider %}
<div class="container" style="margin-top:150px;margin-bottom:150px">
        <div class="row" style="background-color:white;padding:20px 40px;margin:auto;max-width:900px">
            <div class="col-6">
                <form class="text-center"  method="POST">
                    <h3>Lütfen Giriş Yapınız</h3>
                    {% csrf_token %}
                    {{ form }}
                    <br />
                    
                    <button type="submit" class="btn btn-lg btn-success">
                        Giriş Yap
                    </button>
                </form>
                
            </div>
            <div class="col-6">
                <img src="" alt="">
            </div>

        </div>



    </div>
{% endblock slider %}

backend/user_op/templates/ogrenci_anasayfa.html
{% extends "homebase.html" %}